// <auto-generated />
using System;
using BotPlazaVea2._0.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BotPlazaVea2._0.Migrations
{
    [DbContext(typeof(PlazaVeaContext))]
    partial class PlazaVeaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BotPlazaVea2._0.Models.Caracteristicas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("caracteristica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("productoId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("productoId");

                    b.ToTable("Caracteristicas");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Descripciones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("productoId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("productoId");

                    b.ToTable("Descripciones");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Productos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("idUrl")
                        .HasColumnType("integer");

                    b.Property<string>("imagenUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreProducto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("precioOferta")
                        .HasColumnType("numeric");

                    b.Property<decimal>("precioReg")
                        .HasColumnType("numeric");

                    b.Property<bool>("promocion")
                        .HasColumnType("boolean");

                    b.Property<string>("proveedor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subcategoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("subtipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idUrl")
                        .IsUnique();

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Promociones", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("condicion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("productoId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("productoId");

                    b.ToTable("Promociones");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Urls", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pagina")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("url")
                        .IsUnique();

                    b.ToTable("Urls");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Caracteristicas", b =>
                {
                    b.HasOne("BotPlazaVea2._0.Models.Productos", "Productos")
                        .WithMany("caracteristicas")
                        .HasForeignKey("productoId");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Descripciones", b =>
                {
                    b.HasOne("BotPlazaVea2._0.Models.Productos", "Productos")
                        .WithMany("descripciones")
                        .HasForeignKey("productoId");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Productos", b =>
                {
                    b.HasOne("BotPlazaVea2._0.Models.Urls", "Url")
                        .WithOne("Producto")
                        .HasForeignKey("BotPlazaVea2._0.Models.Productos", "idUrl")
                        .HasConstraintName("FK_URL_1");

                    b.Navigation("Url");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Promociones", b =>
                {
                    b.HasOne("BotPlazaVea2._0.Models.Productos", "productos")
                        .WithMany("promociones")
                        .HasForeignKey("productoId");

                    b.Navigation("productos");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Productos", b =>
                {
                    b.Navigation("caracteristicas");

                    b.Navigation("descripciones");

                    b.Navigation("promociones");
                });

            modelBuilder.Entity("BotPlazaVea2._0.Models.Urls", b =>
                {
                    b.Navigation("Producto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
